version: '3.8'

services:
  db:
    image: timescale/timescaledb:latest-pg16
    container_name: profitsense_db
    environment:
      POSTGRES_USER: xxxx
      POSTGRES_PASSWORD: xxxxxxxx
      POSTGRES_DB: xxxx
    ports:
      - "xxxx:xxxx"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped

  redis:
    image: redis:7
    container_name: profitsense_redis
    ports:
      - "xxxx:xxxx"
    volumes:
      - redisdata:/data
    restart: unless-stopped

  qdrant:
    image: qdrant/qdrant:latest
    container_name: profitsense_qdrant
    ports:
      - "xxxx:xxxx"
    volumes:
      - qdrantdata:/qdrant/storage
    restart: unless-stopped

volumes:
  pgdata:
  redisdata:
  qdrantdata:
