"""Initial schema

Revision ID: 069721c84804
Revises: 
Create Date: 2026-03-27 01:21:47.833404

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '069721c84804'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('backtest_results',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('signal_type', sa.String(), nullable=False),
    sa.Column('signal_date', sa.Date(), nullable=False),
    sa.Column('entry_price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('nifty_entry', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('price_10d', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('price_30d', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('price_60d', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('price_90d', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('return_10d', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('return_30d', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('return_60d', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('return_90d', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('nifty_return_10d', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('nifty_return_30d', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('nifty_return_60d', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('alpha_10d', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('alpha_30d', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('alpha_60d', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('success_30d', sa.Boolean(), nullable=True),
    sa.Column('ensemble_score', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('signal_details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_bt_symbol', 'backtest_results', ['symbol', 'signal_date'], unique=False)
    op.create_index(op.f('ix_backtest_results_signal_type'), 'backtest_results', ['signal_type'], unique=False)
    op.create_table('bulk_block_deals',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('deal_type', sa.String(), nullable=True),
    sa.Column('client_name', sa.String(), nullable=True),
    sa.Column('trade_type', sa.String(), nullable=True),
    sa.Column('quantity', sa.BigInteger(), nullable=True),
    sa.Column('price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('value_cr', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('trade_date', sa.Date(), nullable=False),
    sa.Column('raw_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_bulk_symbol', 'bulk_block_deals', ['symbol', 'trade_date'], unique=False)
    op.create_table('corporate_events',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('event_type', sa.String(), nullable=True),
    sa.Column('event_date', sa.Date(), nullable=True),
    sa.Column('ex_date', sa.Date(), nullable=True),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('raw_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('insider_trades',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('person_name', sa.String(), nullable=True),
    sa.Column('person_category', sa.String(), nullable=True),
    sa.Column('transaction_type', sa.String(), nullable=True),
    sa.Column('quantity', sa.BigInteger(), nullable=True),
    sa.Column('avg_price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('total_value', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('holding_before', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('holding_after', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('trade_date', sa.Date(), nullable=False),
    sa.Column('filing_date', sa.Date(), nullable=True),
    sa.Column('source_url', sa.String(), nullable=True),
    sa.Column('raw_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_insider_symbol', 'insider_trades', ['symbol', 'trade_date'], unique=False)
    op.create_table('mf_portfolio_holdings',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('scheme_code', sa.Integer(), nullable=True),
    sa.Column('month_year', sa.String(), nullable=True),
    sa.Column('stock_symbol', sa.String(), nullable=True),
    sa.Column('corpus_pct', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('shares_held', sa.BigInteger(), nullable=True),
    sa.Column('market_value_cr', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mf_schemes',
    sa.Column('scheme_code', sa.Integer(), nullable=False),
    sa.Column('scheme_name', sa.String(), nullable=False),
    sa.Column('amc_name', sa.String(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('sub_category', sa.String(), nullable=True),
    sa.Column('fund_manager', sa.String(), nullable=True),
    sa.Column('launch_date', sa.Date(), nullable=True),
    sa.Column('nav_date', sa.Date(), nullable=True),
    sa.Column('nav', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('aum_cr', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('expense_ratio', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.PrimaryKeyConstraint('scheme_code')
    )
    op.create_table('price_data',
    sa.Column('time', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('exchange', sa.String(), server_default='NSE', nullable=False),
    sa.Column('open', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('high', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('low', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('close', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('volume', sa.BigInteger(), nullable=True),
    sa.Column('adj_close', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.PrimaryKeyConstraint('time', 'symbol')
    )
    op.create_table('quarterly_results',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('quarter', sa.String(), nullable=False),
    sa.Column('result_date', sa.Date(), nullable=True),
    sa.Column('revenue_cr', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('ebitda_cr', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('pat_cr', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('eps', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('eps_estimate', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('eps_surprise_pct', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('revenue_growth_yoy', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('pat_growth_yoy', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('raw_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_result_symbol_quarter', 'quarterly_results', ['symbol', 'quarter'], unique=True)
    op.create_table('signal_events',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('signal_type', sa.String(), nullable=False),
    sa.Column('direction', sa.String(), nullable=True),
    sa.Column('confidence', sa.Integer(), nullable=True),
    sa.Column('xgb_score', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('lgbm_score', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('lstm_score', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('ensemble_score', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('price_at_signal', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('nifty_at_signal', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('headline', sa.String(), nullable=True),
    sa.Column('what_happened', sa.String(), nullable=True),
    sa.Column('why_matters', sa.String(), nullable=True),
    sa.Column('suggested_action', sa.String(), nullable=True),
    sa.Column('risk_factors', sa.String(), nullable=True),
    sa.Column('history_stats', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('trigger_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('shap_features', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('detected_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('expires_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('price_30d', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('price_60d', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('price_90d', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('return_30d', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('return_60d', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('return_90d', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('nifty_return_30d', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('alpha_30d', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('outcome_success', sa.Boolean(), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_signal_events_detected_at'), 'signal_events', ['detected_at'], unique=False)
    op.create_index(op.f('ix_signal_events_direction'), 'signal_events', ['direction'], unique=False)
    op.create_index(op.f('ix_signal_events_signal_type'), 'signal_events', ['signal_type'], unique=False)
    op.create_index(op.f('ix_signal_events_symbol'), 'signal_events', ['symbol'], unique=False)
    op.create_table('stock_fundamentals',
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('company_name', sa.String(), nullable=True),
    sa.Column('sector', sa.String(), nullable=True),
    sa.Column('industry', sa.String(), nullable=True),
    sa.Column('bse_code', sa.Integer(), nullable=True),
    sa.Column('nse_code', sa.String(), nullable=True),
    sa.Column('market_cap_cr', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('pe_ratio', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('pb_ratio', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('ev_ebitda', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('roe', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('roce', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('debt_equity', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('promoter_holding_pct', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('promoter_pledge_pct', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('fii_holding_pct', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('dii_holding_pct', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.PrimaryKeyConstraint('symbol')
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('risk_profile', sa.String(), nullable=True),
    sa.Column('investment_horizon', sa.String(), nullable=True),
    sa.Column('portfolio_value_lakh', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('telegram_chat_id', sa.BigInteger(), nullable=True),
    sa.Column('whatsapp_number', sa.String(), nullable=True),
    sa.Column('alert_preferences', postgresql.JSONB(astext_type=sa.Text()), server_default='{"email":true,"telegram":false,"push":true}', nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('mf_nav_history',
    sa.Column('time', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('scheme_code', sa.Integer(), nullable=False),
    sa.Column('nav', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.ForeignKeyConstraint(['scheme_code'], ['mf_schemes.scheme_code'], ),
    sa.PrimaryKeyConstraint('time', 'scheme_code')
    )
    op.create_table('portfolio_holdings',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('avg_buy_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('buy_date', sa.Date(), nullable=True),
    sa.Column('exchange', sa.String(), server_default='NSE', nullable=False),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_user_symbol', 'portfolio_holdings', ['user_id', 'symbol'], unique=True)
    op.create_table('user_mf_holdings',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('scheme_code', sa.Integer(), nullable=True),
    sa.Column('scheme_name', sa.String(), nullable=True),
    sa.Column('folio_number', sa.String(), nullable=True),
    sa.Column('units', sa.Numeric(precision=14, scale=4), nullable=True),
    sa.Column('avg_nav', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('current_nav', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('invested_amount', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('current_value', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('xirr', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('transactions', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_mf_holdings')
    op.drop_index('idx_user_symbol', table_name='portfolio_holdings')
    op.drop_table('portfolio_holdings')
    op.drop_table('mf_nav_history')
    op.drop_table('users')
    op.drop_table('stock_fundamentals')
    op.drop_index(op.f('ix_signal_events_symbol'), table_name='signal_events')
    op.drop_index(op.f('ix_signal_events_signal_type'), table_name='signal_events')
    op.drop_index(op.f('ix_signal_events_direction'), table_name='signal_events')
    op.drop_index(op.f('ix_signal_events_detected_at'), table_name='signal_events')
    op.drop_table('signal_events')
    op.drop_index('idx_result_symbol_quarter', table_name='quarterly_results')
    op.drop_table('quarterly_results')
    op.drop_table('price_data')
    op.drop_table('mf_schemes')
    op.drop_table('mf_portfolio_holdings')
    op.drop_index('idx_insider_symbol', table_name='insider_trades')
    op.drop_table('insider_trades')
    op.drop_table('corporate_events')
    op.drop_index('idx_bulk_symbol', table_name='bulk_block_deals')
    op.drop_table('bulk_block_deals')
    op.drop_index(op.f('ix_backtest_results_signal_type'), table_name='backtest_results')
    op.drop_index('idx_bt_symbol', table_name='backtest_results')
    op.drop_table('backtest_results')
    # ### end Alembic commands ###
